config/routes.rb
RedmineApp::Application.routes.draw do
    post 'feedback_buttons', to: 'feedback_buttons#create'
    post 'feedback_buttons/satisfaction', to: 'feedback_buttons#satisfaction'
    post 'feedback_buttons/submit_refusal', to: 'feedback_buttons#submit_refusal'

    get 'feedback_buttons/show_issue', to: 'feedback_buttons#show_issue', as: 'show_issue'
    get 'feedback_buttons/approve', to: 'feedback_buttons#approve', as: 'approve'
    get 'feedback_buttons/declined', to: 'feedback_buttons#declined', as: 'declined'
end
  

app/models/mailer.rb
class Mailer < ActionMailer::Base
  default from: 'redmine@unochapeco.edu.br'
  def feedback_email(user, issue, notes)
    @user = user
    @issue = issue
    @notes = notes

    mail(to: @user.mail, subject: "Feedback do chamado ##{@issue.id} - #{@issue.subject} #{@user.name}") do |format|
      format.html { render 'feedback_email' }  # Renderiza o template feedback_email.html.erb
    end
    Rails.logger.info "Email enviado para #{@user.mail}" #Debug
  end
end

app/controllers/feedback_buttons_controller.rb
class FeedbackButtonsController < ApplicationController
  unloadable

  before_action :verify_authenticity_token, except: [:approve]
  before_action :require_login

  RESOLVIDO = 23
  NAO_RESOLVIDO = 36
  NOTA = 21
  SATISFACAO = 22

  def approve
    issue_id = params[:issue_id]
    issue = Issue.find(issue_id)
    relations = IssueRelation.where(issue_from_id: issue.id).first
    closed_status = IssueStatus.find_by(id: RESOLVIDO) # Id status resolvido
    rating_custom_field = IssueCustomField.find_by(id: NOTA) # id do campo personalizado 'NOTA'
    @issue = issue

    if @issue.author_id != User.current.id
      flash[:error] = "Somente o autor do chamado pode aprova-lo."
      redirect_to issue_path(@issue)
      return
    end

    # Valida se o chamado está encerrado e a pesquisa ainda não foi respondida
    if @issue.status_id == closed_status.id && @issue.custom_value_for(rating_custom_field.id).value.blank?
      flash[:notice] = "O chamado já foi aprovado mas seu feedback ainda não foi registrado."
      render 'feedback_buttons/approve' # Renderiza a view
      return
    end

    if @issue.status_id != closed_status.id
      issue.status = closed_status

      if relations.present?
        issue_relation = Issue.find(relations.issue_to_id)
        issue_relation.status = closed_status
      end

      if issue.save && (relations.nil? || issue_relation.save)
        flash[:notice] = "Solução do chamado: <strong>##{@issue.id} - #{@issue.subject}</strong> foi aprovada com sucesso! De seu feedback sobre o atendimento abaixo."
        render 'feedback_buttons/approve' # Renderiza a view
      else
        flash[:error] = "Houve um problema ao salvar o status do chamado."
        redirect_to issue_path(@issue)
      end
    else
      flash[:error] = "Este chamado já foi aprovado ou encerrado anteriormente."
      redirect_to issue_path(@issue)
    end
  end


  def satisfaction
    rating = params[:rating]
    comment = params[:comment]
    issue_id = params[:issue_id]
    @issue = Issue.find(issue_id)

    rating_custom_field = IssueCustomField.find_by(id: NOTA) #Id do campo personalizado NOTA
    comment_custom_field = IssueCustomField.find_by(id: SATISFACAO) #Id do campo personalizado Satisfação

    if @issue && rating_custom_field && comment_custom_field
      @issue.custom_field_values = {
        rating_custom_field.id => rating,
        comment_custom_field.id => comment
      }
    end

    if @issue.save!
      flash[:notice] = "Obrigado pelo feedback!"
    else
      flash[:error] = "Erro ao salvar feedback"
    end

    redirect_to issue_path(@issue)
  end

  def declined
    issue_id = params[:issue_id]
    issue = Issue.find(issue_id)
    relations = IssueRelation.where(issue_from_id: issue.id).first
    refused_status = IssueStatus.find_by(id: NAO_RESOLVIDO) #configurar status de chamado rejeitado

    if relations.present?
      issue_relation = Issue.find(relations.issue_to_id)
      assigned_to = User.find(issue_relation.assigned_to_id)

      last_comment = Journal
                       .where(journalized_id: issue.id, user_id: assigned_to.id, journalized_type: 'Issue')
                       .where.not(notes: [nil, ''])
                       .order(created_on: :desc).first

      @assigned_to = assigned_to
      @last_comment = last_comment
    end

    @issue = issue

    if @issue.author_id != User.current.id
      flash[:error] = "Somente o autor do chamado pode recusa-lo."
      redirect_to issue_path(@issue)
      return
    end

    if @issue.status_id != refused_status.id
      render 'feedback_buttons/declined'
    else
      flash[:error] = "Este chamado já foi recusado anteriormente."
      redirect_to issue_path(@issue)
    end
  end

  def submit_refusal
    issue_id = params[:issue_id]
    refusal_comment = params[:refusal_comment]
    issue = Issue.find(issue_id)
    relations = IssueRelation.where(issue_from_id: issue.id).first
    rejected_status = IssueStatus.find_by(id: NAO_RESOLVIDO) #configurar status de chamado rejeitado
    @issue = issue

    if relations.present?
      issue_relation = Issue.find(relations.issue_to_id)
    end

    if @issue.status_id != rejected_status.id
      issue.status = rejected_status

      if relations.present?
        issue_relation.status = rejected_status
      end

      journal = issue.journals.build(
        notes: refusal_comment,
        user_id: issue.author_id
      )

      if issue.save && (relations.nil? || issue_relation.save) && journal.save
        flash[:notice] = "Solução do chamado: <strong>##{issue.id} - #{issue.subject}</strong> foi recusada."
        redirect_to issue_path(@issue)
      else
        flash[:error] = "Houve um problema ao salvar o status do chamado."
        redirect_to issue_path(@issue)
      end
    else
      flash[:error] = "Este chamado já foi recusado anteriormente."
      redirect_to issue_path(@issue)
    end
  end

  def show_issue
    @issue = Issue.find(params[:issue_id])

    redirect_to issue_path(@issue)
  end
end

app/views/feedback_buttons/approve.html.erb
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Pesquisa de Satisfação</title>
  <style>
      .star-rating {
          direction: rtl;
          display: inline-flex;
          font-size: 2em;
      }

      .star-rating input[type="radio"] {
          display: none;
      }

      .star-rating label {
          color: #ddd;
          cursor: pointer;
          padding: 0 5px;
      }

      .star-rating input[type="radio"]:checked ~ label {
          color: #f5c518;
      }

      .star-rating label:hover,
      .star-rating label:hover ~ label {
          color: #f5c518;
      }
      .desc {
          color: #a8a8a8;
          font-size: 12px;
      }
      textarea {
          border-radius: 5px;
          border: 2px solid #628DB6;
          width: 40%;
          height: 30%;
      }
      button {
          display: inline-block;
          padding: 3px 7px;
          margin: 10px 0;
          font-size: 16px;
          color: #fff;
          text-align: center;
          text-decoration: none;
          border-radius: 5px;
      }
      .button-send {
          background-color: #628DB6 !important;
      }
      .button-send:hover {
          background-color: #346fa8 !important;
      }
      .button-disabled {
          cursor: not-allowed !important;
          opacity: 0.6;
      }
  </style>
</head>
<body>
<h1>Pesquisa de Satisfação</h1>
<p class="desc">Avalie o atendimento prestado no chamado!</p>
<form id="satisfactionForm" action="/feedback_buttons/satisfaction" method="post">
  <input type="hidden" name="authenticity_token" value="<%= form_authenticity_token %>">
  <input type="hidden" name="issue_id" value="<%= @issue.id %>">
  <div class="star-rating">
    <input type="radio" id="star5" name="rating" value="5"><label for="star5">&#9733;</label>
    <input type="radio" id="star4" name="rating" value="4"><label for="star4">&#9733;</label>
    <input type="radio" id="star3" name="rating" value="3"><label for="star3">&#9733;</label>
    <input type="radio" id="star2" name="rating" value="2"><label for="star2">&#9733;</label>
    <input type="radio" id="star1" name="rating" value="1"><label for="star1">&#9733;</label>
  </div>
  <br><br>
  <label for="comment">Comentário:</label><br>
  <p hidden="hidden" id="msg-feedback">Antes de enviar sua nota, fale um pouco sobre a sua satisfação com o atendimento.</p>
  <textarea id="comment" name="comment" rows="4" cols="50"></textarea><br><br>
  <button class="button-send" type="submit">Enviar</button>
</form>

<script>
    document.getElementById('satisfactionForm').addEventListener('submit', function(event) {
        const rating = document.querySelector('input[name="rating"]:checked');
        const comment = document.getElementById('comment').value.trim();

        if (!rating) {
            alert('Por favor, realize a avaliação de satisfação.');
            event.preventDefault();
        }

        if (rating && rating.value <= 3 && comment === '' ) {
            event.preventDefault();
        }
    });

    // Função para atualizar o estado do botão com base na classificação e no comentário
    function updateButtonState() {
        const rating = document.querySelector('input[name="rating"]:checked');
        const comment = document.getElementById('comment').value.trim();
        const msgFeedback = document.getElementById('msg-feedback');
        const submitButton = document.querySelector('.button-send');

        if (parseInt(rating.value) > 3 || comment !== '') {
            msgFeedback.setAttribute('hidden', 'hidden');
            submitButton.classList.remove('button-disabled');
            submitButton.disabled = false;
        } else {
            msgFeedback.removeAttribute('hidden');
            submitButton.classList.add('button-disabled');
            submitButton.disabled = true;
        }
    }

    // Adiciona um ouvinte de evento de clique aos elementos de input de classificação
    document.querySelectorAll('input[name="rating"]').forEach(function(input) {
        input.addEventListener('click', updateButtonState);
    });

    // Adiciona um ouvinte de evento de entrada ao textarea para detectar mudanças
    document.getElementById('comment').addEventListener('input', updateButtonState);
</script>
</body>
</html>

app/views/feedback_buttons/declined.html.erb
<!DOCTYPE html>
<html lang="pt-BR">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Motivo da Recusa</title>
  <style>
      .desc_label {
          display: block;
          margin-bottom: 8px;
          font-weight: bold;
      }
      textarea {
          border-radius: 5px;
          border: 2px solid #628DB6;
          width: 40%;
          height: 30%;
          padding: 10px;
          font-size: 14px;
      }
      button {
          display: inline-block;
          padding: 3px 7px;
          margin: 10px 0;
          font-size: 16px;
          color: #fff;
          text-align: center;
          text-decoration: none;
          border-radius: 5px;
      }
      .button-send {
          background-color: #628DB6 !important;
      }
      .button-send:hover {
          background-color: #346fa8 !important;
      }
      .button-send:disabled {
          background-color: #a1b8d1 !important;
          cursor: not-allowed;
      }
      .card {
          background-color: #f6ffec;
          border: 1px solid #abff5b;
          border-radius: 5px;
          padding: 12px;
          margin-bottom: 20px;
          box-shadow: 0 2px 4px rgba(0, 0, 0, 0.1);
          max-width: 39%;
      }
      .card-header {
          font-weight: bold;
          margin-bottom: 10px;
      }
      .card-content {
          font-size: 14px;
          color: #555;
      }
      .error {
          border-color: red !important;
      }
      .error-message {
          color: red;
          font-weight: bold;
          display: none;
          margin-top: 10px;
      }
  </style>
  <script>
      document.addEventListener('DOMContentLoaded', (event) => {
          const textarea = document.getElementById('reason');
          const errorMessage = document.getElementById('error-message');
          const submitButton = document.querySelector('.button-send');

          textarea.addEventListener('input', () => {
              if (textarea.value.trim().length < 5) {
                  textarea.classList.add('error');
                  errorMessage.style.display = 'block';
                  submitButton.disabled = true;
              } else {
                  textarea.classList.remove('error');
                  errorMessage.style.display = 'none';
                  submitButton.disabled = false;
              }
          });

          submitButton.disabled = true;
      });
  </script>
</head>
<body>
<h1>Motivo da Recusa</h1>
<% if @assigned_to.present? && @last_comment.present? %>
  <div class="card">
    <div class="card-header">
      Último comentário de <%= @assigned_to.firstname %> <%= @assigned_to.lastname %> às <%= @last_comment.created_on.strftime("%d/%m/%Y %H:%M") %>
    </div>
    <div class="card-content">
      <%= @last_comment.notes %>
    </div>
  </div>
<% end %>
<form action="/feedback_buttons/submit_refusal" method="post">
  <input type="hidden" name="authenticity_token" value="<%= form_authenticity_token %>">
  <input type="hidden" name="issue_id" value="<%= @issue.id %>">
  <label class="desc_label" for="reason">Por favor, descreva o motivo da recusa e especifique o que ainda deve ser feito:</label>
  <textarea id="reason" name="refusal_comment" required></textarea>
  <p style="color: red; font-weight: bold;">Nota: A solicitação só será recusada quando você enviar o motivo.</p>
  <p id="error-message" class="error-message">O motivo da recusa deve ter pelo menos 5 caracteres.</p>
  <button class="button-send" type="submit">Enviar Motivo</button>
</form>
</body>
</html>

app/views/issues/_feedback_buttons.html.erb
<!--  29 = Status "Aguardando Feedback" 26 = Projeto "Chamados"-->
<% if @issue.status.id == 29 && @issue.project_id == 26 %>
  <style>
      .btn {
          display: inline-block;
          padding: 3px 7px;
          font-size: 16px;
          color: #fff !important;
          text-align: center;
          text-decoration: none;
          border-radius: 5px;
      }
      .button-send {
          background-color: #628DB6 !important;
      }
      .button-send:hover {
          background-color: #346fa8 !important;
      }
      .button-decline {
          background-color: #f65549;
      }
      .button-decline:hover {
          background-color: #fa493c;
      }
      .box-btn {
          margin-bottom: 20px;
      }
  </style>

  <div class="box-btn" id="feedback-buttons">
    <p><strong>Chamado aguardando aprovação:</strong></p>
    <%= hidden_field_tag :issue_id, @issue.id, id: 'issue_id' %>
    <a href="<%= approve_url(issue_id: @issue.id) %>" target="_blank" class="btn button-send">Aprovar</a>
    <a href="<%= declined_url(issue_id: @issue.id) %>" target="_blank" class="btn button-decline">Recusar</a>
  </div>
<% end %>